### ISSUE TITLE
Not being able to load map

### ISSUE THREAD

**Issue by Usama5226** [ticketevolution/seatmaps-client#287]
Hi @jwcobb @mxweaver,

I'm trying to use this library on my WordPress site but it not displaying the map getting the below error in the console could you please help.

```
jsdelivr-header.js:7 Uncaught ReferenceError: require is not defined
    at jsdelivr-header.js:7:1
(anonymous) @ jsdelivr-header.js:7Understand this error
2467264/:126 Uncaught TypeError: Tevomaps is not a constructor
    at HTMLDocument.<anonymous> (2467264/:126:31)
```

```
<?php

require get_template_directory() . '/vendor/autoload.php';

use TicketEvolution\Client as TEvoClient;

$url = $_SERVER['REQUEST_URI'];
$path = parse_url($url, PHP_URL_PATH);
$categories = explode('/', $path)[2];

$apiClient = new TEvoClient([
    'baseUrl'     => 'https://api.sandbox.ticketevolution.com/',
    'apiVersion'  => 'v9',
    'apiToken'    => 'dd6b5e4de1ea203839dda54acd76b4b2',
    'apiSecret'   => '9A5ZGgekTQ7yBBSAMAlv/PPdXtxr456d0v4dCUiD',
]);

// Fetch event data
$response = $apiClient->showEvent([
    'event_id' => (int)$categories,
]);

// Debugging output
$event = $response; // Assign response directly to event

// Fetch listings data
$listingsResponse = $apiClient->listings([
    'event_id' => (int)$categories,
]);

// Debugging output
$tickets = isset($listingsResponse['listings']) ? $listingsResponse['listings'] : [];

?>

<!DOCTYPE html>
<html>
<head>
    <title><?php echo $event ? $event['name'] : 'Event Not Found'; ?></title>
</head>
<body>
    <h1><?php echo $event ? $event['name'] : 'Event Not Found'; ?></h1>
    <p>Date and Time: <?php echo $event ? $event['occurs_at_local'] : 'N/A'; ?></p>
    <p>Venue: <?php echo $event ? $event['venue']['name'] . ' in ' . $event['venue']['location'] : 'N/A'; ?></p>
    <?php if ($event && isset($event['configuration']['seating_chart']['large'])) : ?>
        <img src="<?php echo $event['configuration']['seating_chart']['large']; ?>" alt="Seating Chart">
    <?php else: ?>
        <p>No seating chart available.</p>
    <?php endif; ?>

    <h2>Available Tickets</h2>
    <?php if (!empty($tickets)) : ?>
        <table>
            <thead>
                <tr>
                    <th>Section</th>
                    <th>Row</th>
                    <th>Quantity</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tickets as $ticket) : ?>
                <tr>
                    <td><?php echo $ticket['section']; ?></td>
                    <td><?php echo $ticket['row']; ?></td>
                    <td><?php echo $ticket['available_quantity']; ?></td>
                    <td>$<?php echo $ticket['retail_price']; ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else : ?>
        <p>No tickets available.</p>
    <?php endif; ?>

    <?php if ($event && isset($event['venue']['id'], $event['configuration']['id'])) : ?>
        <div id="my-map" style="height: 500px; width: 100%;"></div>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var seatmap = new Tevomaps({
                    venueId: "<?php echo $event['venue']['id']; ?>",
                    configurationId: "<?php echo $event['configuration']['id']; ?>",
                    ticketGroups: [
                        <?php foreach ($tickets as $ticket) : ?>
                        {
                            tevo_section_name: "<?php echo $ticket['section']; ?>",
                            retail_price: <?php echo $ticket['retail_price']; ?>,
                        },
                        <?php endforeach; ?>
                    ],
                });

                var seatmapApi = seatmap.build("my-map");
            });
        </script>
    <?php else : ?>
        <p>Seatmap not available.</p>
    <?php endif; ?>
</body>
</html>

<?php get_footer(); ?>

```

Thanks.

**Comment by Usama5226** [comment]
Hi @coneybeare,

Hopefully, you are doing great.

In the Readme file, you mentioned downloading `tevomaps.js` from https://raw.githubusercontent.com/ticketevolution/seatmaps-client/master/build/tevomaps.js but there is no file found could you please help me with this?

Thanks.

**Comment by jwcobb** [comment]
I've disabled your API credential since you posted it publicly. Please contact your sales contact and ask for another one and secure it properly.

**Comment by Usama5226** [comment]
@jwcobb Sorry I overlooked that. Can you please give me any information about my issue??

**Comment by jwcobb** [comment]
The issue appears to be with your JS. The seatmaps are up and running on hundreds of sites so I do not believe it is a bug in the project code.

**Comment by Usama5226** [comment]
@jwcobb I followed all the instructions using the Window Object method, but the `tevomaps.js` file mentioned by @coneybeare in the README resulted in a 404 error.
https://github.com/ticketevolution/seatmaps-client/commit/bfc4fd8c7283b6b34b0906fefa269849b348dbb7

**Comment by coneybeare** [comment]
404 from https://cdn.jsdelivr.net/npm/@ticketevolution/seatmaps-client/cjs/index.min.js ? Can you not access that url?

**Comment by coneybeare** [comment]
It seems that you are reading the deleted code as part of that PR, not the updated code. You can find instructions on the [readme](https://github.com/ticketevolution/seatmaps-client/blob/master/README.md)

**Comment by Usama5226** [comment]
@coneybeare Thanks for the reply.

only using this code results to these errors:

```
jsdelivr-header.js:7 Uncaught ReferenceError: require is not defined
    at jsdelivr-header.js:7:1
(anonymous) @ jsdelivr-header.js:7Understand this error
2467264/:126 Uncaught TypeError: Tevomaps is not a constructor
    at HTMLDocument.<anonymous> (2467264/:126:31)
```

```
<div id="my-map"></div>
<script src="https://cdn.jsdelivr.net/npm/@ticketevolution/seatmaps-client/cjs/index.min.js"></script>
<script>
  // create a new seatmap
  var seatmap = new Tevomaps({
    venueId: "10",
    configurationId: "1046",
    ticketGroups: [
      {
        tevo_section_name: "upper end zone 232",
        retail_price: 100,
      },
    ],
  });

  // turn element with ID of 'my-map' into a seatmap for config 1046
  var seatmapApi = seatmap.build("my-map");

  // perform some actions, like highlighting section "upper end zone 232"
  seatmapApi.highlightSection("upper end zone 232");
</script>
```

**Comment by Usama5226** [comment]
Can anyone help??

**Comment by coneybeare** [comment]
We will likely need to repackage that version for client side `require` if you need it. As a workaround until we can do that, you can try adding something like https://www.npmjs.com/package/clientside-require before ours.

**Comment by coneybeare** [comment]
You can try it out and see. You can also try this old version, though not sure it it will work for your scenario: https://cdn.jsdelivr.net/npm/@ticketevolution/seatmaps-client@1.3.4/build/tevomaps.min.js

**Comment by Usama5226** [comment]
Thanks for your help, I really appreciate it. @coneybeare
